### ISSUE TITLE
Where should I put these two files? Thank you for your answer

### ISSUE THREAD

**Issue by 7zoo** [Acly/comfyui-inpaint-nodes#56]
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/171459115/2ceeb056-4a83-4957-beec-607fb28cfae3)

**Comment by elvizlai** [comment]
*.patch file not found even I put it in models/inpaint folder after upgrading ComfyUI to latest.

**Comment by niu211** [comment]
![image](https://github.com/Acly/comfyui-inpaint-nodes/assets/132815137/714392c8-3ccb-40db-a801-3162d54ae6a3)
I also found the same problem after upgrading. These two files are not recognized.

**Comment by Acly** [comment]
They're still listed for me, latest ComfyUI (a82fae2375744a73d63268bc4e167649e3f026e0)

**Comment by elvizlai** [comment]
that's strange, I use the same version(a82fae2375744a73d63268bc4e167649e3f026e0), and I check out ComyUI to 7 day's ago and restart, the patch file still NOT listed. Maybe another nodes changed the "_add_folder_path"?

**Comment by Acly** [comment]
Makes sense. Those nodes overwrite the list of allowed file extensions for the `inpaint` folder. If they are loaded afterwards, `.patch` is no longer valid.

[Here](https://github.com/Acly/comfyui-inpaint-nodes/blob/main/__init__.py#L5-L19) is how I do it, which extends extensions from other custom nodes rather than overwriting them.
